### ISSUE TITLE
Local File Inclusion

### ISSUE THREAD

**Issue by ProfFan** [luigifreitas/LatexBot#2]
After some experiment, I discovered that your bot allows the latex binary to access every file on the file system, and the latex binary is probably running as root. This makes any user to read arbitrary file on your server. Try `/convert \text{\input{/etc/shadow}}`. Maybe you should put the process in a container and only give it lower access level.

**Comment by luigifcruz** [comment]
@ProfFan Nice finding. I ran some tests and found out that this method can only access files inside the container image. This is happening because I forgot to put the _textlive_ on _paranoid_ mode. Thanks to report this 😃

**Comment by luigifcruz** [comment]
Error patched.
